site_title = "Wenxun-Arxiv"
limit_days = 7
cache_url = "https://github.com/zhaowenxun/WenxunPrivateArxiv/blob/gh-pages/cache.json"

[[sources]]
limit = 150
title = "nerf"

[[sources]]
limit = 150
title = "hdr"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
