site_title = "Wenxun-Arxiv"
limit_days = 30
cache_url = "https://github.com/adaxun/WenxunPrivateArxiv/blob/gh-pages/cache.json"

[[sources]]
limit = 50
category = "cs.CV+AND+abs:sdf+OR+ti:sdf"
title = "SDF"

[[sources]]
limit = 50
category = "cs.CV+AND+abs:mesh+OR+ti:mesh"
title = "Mesh"

[[sources]]
limit = 50
category = "cs.CV+AND+abs:nerf+OR+ti:nerf"
title = "NeRF"

[[sources]]
limit = 50
category = "cs.CV+AND+abs:hdr+OR+ti:hdr"
title = "HDR"

[[sources]]
limit = 50
category = "cs.CV+AND+abs:iqa+OR+ti:image+quality"
title = "IQA"

[[sources]]
limit = 50
category = "cs.CV+AND+abs:deblur+OR+ti:deblur"
title = "Deblur"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
highlight_summary="scripts/highlight_summary.rhai"
